### ISSUE TITLE
First * alone

### ISSUE THREAD

**Issue by ggsilva28** [thiagoprz/ionic-input-mask#3]
Mask does not work properly if first * is followed by a formatting character.

Example
 <ion-input formControlName="tag" mask="*.*.*" [(ngModel)]="form.tag" [maxlength]="5"></ion-input>

The mask for the first dot is not replaced
if i type in the value 150 the expected result would be "1.5.0"
however the first dot doesnt work resulting in "150" and if i keep typing it would result in "150.0"

**Comment by thiagoprz** [comment]
Hey @ggsilva28, can you please check my [PR](https://github.com/thiagoprz/ionic-input-mask/pull/4)
