### ISSUE TITLE
Not enforcing numbers?

### ISSUE THREAD

**Issue by tattivitorino** [thiagoprz/ionic-input-mask#5]
this mask does not enforce numbers.. 
```
<ion-input #inputPhone
formControlName="phone"
type="text"
inputmode="numeric"
enterkeyhint="done"
clear-input="true"
maxlength="13"
mask="** ***** ****"></ion-input>
```
this will allow user to enter any character!

**Comment by thiagoprz** [comment]
Hey, you can implement this enforcement by just using type="tel" for instance.

**Comment by luiz-felipe-moreira** [comment]
Using type="tel" only works on a mobile device, because the browser on mobile device can present a keyboard optimized for entering  numbers. On a desktop computer, the user is still allowed to enter any character.

**Comment by thiagoprz** [comment]
> Using type="tel" only works on a mobile device, because the browser on mobile device can present a keyboard optimized for entering numbers. On a desktop computer, the user is still allowed to enter any character.

You could add your own keypress event listener like this:

Template html file:
```
<ion-input type="tel" (keypress)="numericOnly($event)"></ion-input>
```

And on the typescript page:
```
numericOnly(event): boolean {
   let pattern = /^([0-9])$/;
   let result = pattern.test(event.key);
   return result;
}
```

Bear in mind I haven't tested this since I have not being using Ionic for Desktop or Web applications recently. But I guess from this idea you could easily get some sort of solution.
